apiVersion: apps/v1
kind: Deployment
metadata:
  name: snakegame
spec:
  selector:
    matchLabels:
      app: snakegame
  template:
    metadata:
      labels:
        app: snakegame
    spec:
      containers:
      - name: snakegame
        image: 444062204470.dkr.ecr.eu-central-1.amazonaws.com/snakegame:v1
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 81
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  annotations:
    # This tells the controller to create an IP-based Load Balancer for Fargate
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: snakegame
  ports:
    - port: 80
      targetPort: 81